### PR TITLE
LSFF model 6 baseline validation

### PR DESCRIPTION
**Pull request by alibow**

### CODE REVIEW

**Comment by NathanielBlairStahn** [comment]
@alibow I see no dots above the mean CSMR for NTDs in the early neonatal age group -- how is this possible (i.e.not _all_ the draws can be below average)?  Are there some draws that we can't see in this image?

image

Also, it seems strange that CSMR and EMR are validating well for NTDs when the birth prevalence and prevalence are low.  It seems like if not enough people are getting NTDs, then the number of people dying from them should also be too low.  @aflaxman Any idea what could be going on here?

**Comment by aflaxman** [comment]
I think EMR could work right even if prevalence is off, but I agree that it is surprising that CSMR _and_ EMR would match the artifact when prevalence doesn't.  Maybe there is something wrong with the way we are calculating prevalence.

Regarding the dots, there must be some with y-value higher than the y-max of the chart.  Or else something really weird is going wrong...

**Comment by alibow** [comment]
@NathanielBlairStahn @aflaxman in my latest commit, I confirmed that there are some observations for the early neonatal NTD CSMR that are above the max ylim by looking up the values and comparing to the axis limit.

Also, my previous notebook did not stratify by sex because I thought that the plot was easier to interpret, but I added another notebook that stratifies by sex. Because some of the NTD parameters vary by a factor of 10 by sex, I think this might have contributed to the low prevalence/good CSMR&EMR, although the trend still does exist when I stratify by sex too. 

I made sure that prevalence did not depend on whether prevalence calculations were performed using the person time or the state person time data frame.

**Comment by alibow** [comment]
@NathanielBlairStahn @aflaxman, oh, I also forgot to mention that vitamin A deficiency IS actually validating well! There was previously an issue in my code about how the 'cat1' versus 'cat2' exposures were handled. Now that that is fixed it's looking good. 👍

**Comment by aflaxman** [comment]
Yay!

**Pull request merged**
